# 🐼 Pandas I: Fundamentos y Manipulación de Datos

**Pandas** es la librería estándar para la manipulación y análisis de datos en Python. Es como tener un Excel supervitaminado dentro de tu código.

**Objetivos de la sesión:**
1. Entender las estructuras: **Series** y **DataFrames**.
2. Cargar datos desde archivos externos (CSV, JSON).
3. Inspeccionar datos (el concepto de `shape`).
4. Seleccionar y filtrar información (`loc`, `iloc`).
5. Ordenar y manipular columnas.

---

In [2]:
import pandas as pd
import numpy as np

## 1️⃣ Series: La columna vertebral

Una **Serie** es un array unidimensional (como una lista) pero con un índice explícito. Es la pieza fundamental de un DataFrame (un DataFrame es una colección de Series).

Podemos crear una Serie desde una lista o un diccionario.

In [14]:
# 1. Creating from a List
values = [10, 20, 30, 40]
s_list = pd.Series(values, index=['a', 'b', 'c', 'd'])

print("Series from List:\n", s_list)
print("\nAccessing by label 'b':", s_list['b'])

Series from List:
 a    10
b    20
c    30
d    40
dtype: int64

Accessing by label 'b': 20

In [15]:
# 2. Creating from a Dictionary
# Keys become the Index, Values become the Data
data_dict = {'Apple': 100, 'Banana': 200, 'Cherry': 150}
s_dict = pd.Series(data_dict)

print("Series from Dict:\n", s_dict)

Series from Dict:
 Apple     100
Banana    200
Cherry    150
dtype: int64

### Atributos de una Serie
Es útil separar los valores del índice.

In [16]:
print("Values:", s_dict.values)
print("Index:", s_dict.index)

Values: [100 200 150]
Index: Index(['Apple', 'Banana', 'Cherry'], dtype='object')

---

## 2️⃣ DataFrames: La Tabla de Datos

Un **DataFrame** es una estructura tabular bidimensional (filas y columnas). Es lo más parecido a una hoja de cálculo.

Generalmente se crean a partir de un **Diccionario de Listas**, donde:
* Las **Claves** (Keys) son los nombres de columnas.
* Los **Valores** (Values) son listas con los datos.

In [19]:
# Creating a DataFrame manually
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, np.nan, 40],
    'City': ['New York', 'Paris', 'London', 'Tokyo'],
    'Salary': [50000, 60000, 70000, 80000]
}

df_manual = pd.DataFrame(data)
display(df_manual)

      Name   Age      City  Salary
0    Alice  25.0  New York   50000
1      Bob  30.0     Paris   60000
2  Charlie   NaN    London   70000
3    David  40.0     Tokyo   80000

---

## 3️⃣ Lectura de Archivos (I/O)

En el mundo real, cargamos datos externos. Pandas soporta CSV, Excel, JSON, SQL, etc.

Para este ejemplo, usaremos archivos locales.

In [21]:
# Reading CSV
# If you don't have a file, we can create a dummy one for the example
df = pd.read_csv('personas.csv')

print("Loaded from CSV:")
display(df.head(2))

Loaded from CSV:

  Nombre  Edad  Ciudad
0    Ana    25    Lima
1   Luis    30  Bogotá

In [26]:
# Reading JSON
df_json = pd.read_json('gente.json')

print("Loaded from JSON:")
display(df_json.head())

Loaded from JSON:

  nombre  edad                intereses
0    Ana    25  [lectura, programación]
1   Luis    30       [deportes, música]
2  María    22             [arte, cine]

---

## 4️⃣ Inspección de Datos: El primer paso

Antes de analizar nada, debemos entender qué tenemos delante: dimensiones, tipos de datos, valores nulos...

In [38]:
# Let's use a larger dataset (Manual creation for demo purposes if file is missing)
rows_n, cols = np.random.randint(0, 100, size=(100, 5)), ['A', 'B', 'C', 'D', 'E']

df_large = pd.DataFrame(rows_n, columns=cols)

# 1. First rows
display(df_large.head(3))

# 2. Last rows
display(df_large.tail(3))

# 3. Random sample
display(df_large.sample(3))

    A   B   C   D   E
0  66  81  39  23  52
1  45  69   6   7  96
2  64  11  87  36  64

     A   B   C   D   E
97   3  12  12  83  71
98   5  42  33  25  82
99  73  19  43  61  60

     A   B   C   D   E
97   3  12  12  83  71
85  88  75  14  79  87
95  27  84  79  16  63

In [30]:
# 4. Structural Info (Dtypes and Nulls)
df_large.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       100 non-null    int64
 1   B       100 non-null    int64
 2   C       100 non-null    int64
 3   D       100 non-null    int64
 4   E       100 non-null    int64
dtypes: int64(5)
memory usage: 4.0 KB

In [35]:
# 5. Statistical Summary (Mean, Max, Min...)
df_large.describe()

                A           B           C           D          E
count  100.000000  100.000000  100.000000  100.000000  100.00000
mean    49.130000   49.110000   48.590000   50.920000   50.47000
std     27.320638   28.298872   29.808851   28.366177   28.08697
min      0.000000    0.000000    1.000000    1.000000    0.00000
25%     32.000000   25.750000   22.000000   30.500000   27.75000
50%     45.000000   48.500000   45.000000   51.500000   51.50000
75%     74.250000   70.500000   73.250000   75.250000   70.00000
max     98.000000   99.000000   99.000000   99.000000   99.00000

### ⚠️ Concepto Clave: Shape y Shape[0]

La propiedad `.shape` nos devuelve una tupla con las dimensiones del DataFrame: `(filas, columnas)`.

Es vital saber usar `shape[0]` para obtener programáticamente el **número de filas** (muy usado en bucles, validaciones o para calcular porcentajes).

In [39]:
# Getting dimensions
dimensions = df_large.shape
print("Shape (Tuple):", dimensions)

# Accessing specific dimensions
rows = df_large.shape[0]
cols = df_large.shape[1]

print(f"\nThe DataFrame has {rows} rows and {cols} columns.")

# Example usage: Percentage
print(f"Processing row 10 out of {rows}...")

Shape (Tuple): (100, 5)

The DataFrame has 100 rows and 5 columns.
Processing row 10 out of 100...

---

## 5️⃣ Selección e Indexación: El Bisturí

Pandas ofrece múltiples formas de seleccionar datos. Es fácil confundirse, así que hay que tener claro:
1.  **`[]` (Corchetes):** Selección de Columnas.
2.  **`.iloc`:** Selección por **Posición** (Índice numérico).
3.  **`.loc`:** Selección por **Etiqueta** (Nombre).

In [41]:
display(df_large["A"].head(3))

0    66
1    45
2    64
Name: A, dtype: int64

In [42]:
# A) Column Selection
# Returns a Series
col_a = df_large['A']

# Returns a DataFrame (Double brackets)
cols_subset = df_large[['A', 'C', 'E']]

display(cols_subset.head(3))

    A   C   E
0  66  39  52
1  45   6  96
2  64  87  64

In [44]:
# B) Position Selection (.iloc)
# Syntax: [rows_range, cols_range]
# Remember: Python slices exclude the last number

# First 5 rows, first 3 columns
display(df_large.iloc[0:5, 0:3])

# Specific rows and columns (e.g., row 10, column 2)
print("Value at [10, 2]:", df_large.iloc[10, 2])

# Specific rows and columns (e.g., row 4, column 2)
print("Value at [4, 2]:", df_large.iloc[4, 2])

    A   B   C
0  66  81  39
1  45  69   6
2  64  11  87
3  21  52  29
4  68  29  41

Value at [10, 2]: 22
Value at [4, 2]: 41

In [45]:
# C) Label Selection (.loc)
# Syntax: [row_names, col_names]
# Note: .loc INCLUDES the last element in the slice

# Rows 0 to 5 (inclusive), Columns 'A' and 'D'
display(df_large.loc[0:5, ['A', 'D']])

    A   D
0  66  23
1  45   7
2  64  36
3  21  55
4  68  42
5  16  17

### 🧠 Ejercicio 1: Selección
Usando `df_large`:
1. Selecciona las columnas 'B' y 'E'.
2. Muestra las filas de la 50 a la 55 usando `.iloc`.
3. Muestra el valor de la fila 0 y la columna 'A' usando `.loc`.

In [ ]:
# Your code here

---

## 6️⃣ Filtrado Básico (Máscaras Booleanas)

El poder real de Pandas es filtrar filas basándonos en condiciones (similar al `WHERE` en SQL).

In [48]:
# 1. Create a boolean mask
# This returns a Series of True/False
mask = df_large['A'] > 50
print("Mask sample:\n", mask.head())

# 2. Apply the mask to the DataFrame
filtered_df = df_large[mask]
display(filtered_df.head(3))

print(f"\nOriginal rows: {df_large.shape[0]}")
print(f"Filtered rows: {filtered_df.shape[0]}")

Mask sample:
 0     True
1    False
2     True
3    False
4     True
Name: A, dtype: bool

    A   B   C   D   E
0  66  81  39  23  52
2  64  11  87  36  64
4  68  29  41  42  25

Original rows: 100
Filtered rows: 48

In [49]:
# 1. Create a boolean mask
# This returns a Series of True/False
filtered_df = df_large[df_large['A'] > 50]
display(filtered_df.head(3))
print(f"\nOriginal rows: {df_large.shape[0]}")
print(f"Filtered rows: {filtered_df.shape[0]}")

    A   B   C   D   E
0  66  81  39  23  52
2  64  11  87  36  64
4  68  29  41  42  25

Original rows: 100
Filtered rows: 48

In [59]:
# Multiple conditions
# AND (&), OR (|), NOT (~)
# Parentheses are MANDATORY

complex_filter_df = df_large[(df_large['A'] > 50) & (df_large['B'] < 20) & ~(df_large['C'] <= 50)][["A","B"]]
display(complex_filter_df.head())
complex_filter_df.shape[0]

     A   B
2   64  11
67  75  12

2

---

## 7️⃣ Ordenación (Sorting)

Podemos ordenar el DataFrame por los valores de una o varias columnas.

In [66]:
# Ascending sort
df_sorted = df_large.sort_values(by='A', ascending=False) # Ascending by default is True
display(df_sorted.head())

     A   B   C   D   E
52  97  67  97  53  51
14  95  66  74  81  95
62  95  80   4  78  13
20  95  55  11  28  53
21  92  48  75  66  40

In [67]:
# Sorting by multiple columns
df_multi_sort = df_large.sort_values(by=['A', 'B'], ascending=[False, True])
display(df_multi_sort.head())

     A   B   C   D   E
52  97  67  97  53  51
20  95  55  11  28  53
14  95  66  74  81  95
62  95  80   4  78  13
21  92  48  75  66  40

## 🏆 Práctica Final

1. Crea una nueva columna llamada `Suma` que sea la suma de 'A' + 'B'.
2. Filtra las filas donde `Suma` sea mayor a 100.
3. Ordena el resultado por la columna `C` de forma descendente.
4. Guarda el resultado en un archivo `resultado.csv`.

In [ ]:
# Your solution here